### PR TITLE
Demo: Single dynamically-configured demo

### PR DESCRIPTION
**Pull request by skye2k2**
Remove all extra one-off demos, in lieu of having a single, fully configurable demo.
Refactor Prism code generator into reusable function.
Add generateDialog() function to create a configured dialog on-the-fly.
Add TODO placeholders for needed functionality.

### CODE REVIEW

**Comment by rosemariesadler** [comment]
There's some more dom to write, but after that, I think this demo page is done!

**Comment by skye2k2** [comment]
Thanks for updating things, @rosemariesadler, but I am confused as to why my JSDoc-umentation and e --> evt renames were removed

**Comment by rosemariesadler** [comment]
Crud - I specifically didn't add those when I did the commit. The script that runs on commit builds and adds everything. -.- that's not the first time that has happened to me. I'm thinking it may be time to turn that off and then just have to be responsible before committing.

**Comment by rosemariesadler** [comment]
In the end I don't think it'll matter because in the master branch fs-dialog.html is deleted.

**Pull request merged**
