### PR TITLE
TW-764: bugfixes for toggle of dialogs

### PR DESCRIPTION
**Pull request by rosemariesadler**
* rename e to event
* remove attachedToElementClicked from close function because it was causing it to always be false when we use it
* add back in dialog.cancelFocusback - it got removed in a bad copy/paste a while back
* make the open function wait for a setTimout after the first open to fix toggle on touch devices
* add disappearing button to demo to test the bug where we see the dialogs closing when clicking a button inside a dialog that disappears

## To-Dos
- [ ] Tests
- [x] Update demo
- [x] Update documentation & README
- [x] Increment version in bower.json & package.json.

### CODE REVIEW

**Comment by rosemariesadler** [comment]
we may need some new tests - but the current ones are passing still.

**Comment by timothydm42** [comment]
Sorry to bother, but I believe `composedPath` implemented in this PR is causing an error on home app in Edge.

1. Using Edge, on Logged in home page
2. click a person name, like the ones in recommended tasks
3. dialog appears
4. click outside of the dialog
5. dialog doesn't close
6.  examine the error log in Edge dev tools, says 'object does not support property or method composedPath'

thanks

**Comment by skye2k2** [comment]
@timothydm42: Did the break actually occur here? Because `fs-dialog` was already using Event.composedPath prior to this PR.

@rosemariesadler: We likely either need to look into a polyfill (https://github.com/DieterHolvoet/event-propagation-path) or for the reason that either the event or event propotpye are being mangled.

**Comment by timothydm42** [comment]
You're right. I am uncertain whether the break occurred here.

**Pull request merged**
