### PR TITLE
fixed TW-2156, no scroll on dialog

### PR DESCRIPTION
**Pull request by trosales27**
Fixes: https://almtools.ldschurch.org/fhjira/browse/TW-2156

### CODE REVIEW

**Comment by rosemariesadler** [comment]
Haven't actually tested this yet, but I have high suspicions that this will break our sticky header/footer behavior that we built in to fs-dialog.

**Comment by rosemariesadler** [comment]
Okay - this does not break sticky header/footer like I suspected, however it does add an extra, always present (even when dialogs do not need scrolling), scrollbar in windows browsers, which is not going to be an acceptable solution. Because fs-dialog is non shadow dom, you can add this style in your component that consumes fs-dialog (I would probably add overflow auto instead though so that the scrollbar isn't always there even when scrolling isn't necessary), or you can remove the wrapping `<section>` elements in your consuming components so you'll get back the sticky header/footer with scrolling.

**Comment by jlubean** [comment]
I agree with Rose.

**Comment by drewswaycool** [comment]
This message can be ignored.

**Pull request closed without merging**
