### PR TITLE
Fix frontier dist build - Stop minifying files

### PR DESCRIPTION
**Pull request by tylergraf**
This fixes the `gulp dist` build in frontier.

## Changes
* asset manifest includes only files needed (`inert/index.html` was breaking the minifier
* stop minifying html, css and js. (this was breaking the build because the minifier would ignore the file and therefore not replace the imports with the new hashed file names.

### CODE REVIEW

**Comment by crowtherdr** [comment]
I'm not sure what to think about all of the CodeClimate issues. Please DO NOT do a squash and merge when merging this to preserve @tylergraf's work.

**Comment by skye2k2** [comment]
Code Climate by default ignores files that appear to be minified.

**Comment by tylergraf** [comment]
Can we ignore the file in code climate?

**Comment by skye2k2** [comment]
Yes, butwhy would you _not_ want analysis on production files?

**Comment by redbugz** [comment]
You could ignore the files that are compiled by babel, leave analysis on the src files.

**Comment by skye2k2** [comment]
I guess since it's just Babel-transpiling, now, I am fine with that. Generally, I prefer to have analysis on production files that have pieces manipulated by 'hand', like when we collapse whitespace, remove comments, and split and concatenate multiple files. 

Because, if something changes out from under you or is misconfigured to the point of causing errors, static analysis will catch it. 

These errors will only be reported once, unless the corresponding lines are changed, again.

**Comment by tylergraf** [comment]
I don't really care either way. I'm fine leaving them in.

**Pull request merged**
